################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

ELF_SRCS := 
OBJ_SRCS := 
S_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
CYCLO_FILES := 
SIZE_OUTPUT := 
OBJDUMP_LIST := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
MAP_FILES := 
S_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Core/Src \
Core/Startup \
Drivers/BSP/Components/lan8742 \
Drivers/STM32H7xx_HAL_Driver/Src \
LWIP/App \
LWIP/Target \
Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS \
Middlewares/Third_Party/FreeRTOS/Source \
Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F \
Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang \
Middlewares/Third_Party/LwIP/src/api \
Middlewares/Third_Party/LwIP/src/apps/mqtt \
Middlewares/Third_Party/LwIP/src/core \
Middlewares/Third_Party/LwIP/src/core/ipv4 \
Middlewares/Third_Party/LwIP/src/core/ipv6 \
Middlewares/Third_Party/LwIP/src/netif \
Middlewares/Third_Party/LwIP/src/netif/ppp \
Middlewares/Third_Party/LwIP/system/OS \
Middlewares/lvgl/src/core \
Middlewares/lvgl/src/display \
Middlewares/lvgl/src/draw/dma2d \
Middlewares/lvgl/src/draw \
Middlewares/lvgl/src/draw/nema_gfx \
Middlewares/lvgl/src/draw/nxp/g2d \
Middlewares/lvgl/src/draw/nxp/pxp \
Middlewares/lvgl/src/draw/nxp/vglite \
Middlewares/lvgl/src/draw/opengles \
Middlewares/lvgl/src/draw/renesas/dave2d \
Middlewares/lvgl/src/draw/sdl \
Middlewares/lvgl/src/draw/sw/blend/helium \
Middlewares/lvgl/src/draw/sw/blend \
Middlewares/lvgl/src/draw/sw/blend/neon \
Middlewares/lvgl/src/draw/sw \
Middlewares/lvgl/src/draw/vg_lite \
Middlewares/lvgl/src/drivers/display/drm \
Middlewares/lvgl/src/drivers/display/fb \
Middlewares/lvgl/src/drivers/display/ft81x \
Middlewares/lvgl/src/drivers/display/ili9341 \
Middlewares/lvgl/src/drivers/display/lcd \
Middlewares/lvgl/src/drivers/display/renesas_glcdc \
Middlewares/lvgl/src/drivers/display/st7735 \
Middlewares/lvgl/src/drivers/display/st7789 \
Middlewares/lvgl/src/drivers/display/st7796 \
Middlewares/lvgl/src/drivers/display/st_ltdc \
Middlewares/lvgl/src/drivers/evdev \
Middlewares/lvgl/src/drivers/glfw \
Middlewares/lvgl/src/drivers/libinput \
Middlewares/lvgl/src/drivers/nuttx \
Middlewares/lvgl/src/drivers/qnx \
Middlewares/lvgl/src/drivers/sdl \
Middlewares/lvgl/src/drivers/uefi \
Middlewares/lvgl/src/drivers/wayland \
Middlewares/lvgl/src/drivers/windows \
Middlewares/lvgl/src/drivers/x11 \
Middlewares/lvgl/src/font \
Middlewares/lvgl/src/indev \
Middlewares/lvgl/src/layouts/flex \
Middlewares/lvgl/src/layouts/grid \
Middlewares/lvgl/src/layouts \
Middlewares/lvgl/src/libs/barcode \
Middlewares/lvgl/src/libs/bin_decoder \
Middlewares/lvgl/src/libs/bmp \
Middlewares/lvgl/src/libs/expat \
Middlewares/lvgl/src/libs/ffmpeg \
Middlewares/lvgl/src/libs/freetype \
Middlewares/lvgl/src/libs/fsdrv \
Middlewares/lvgl/src/libs/gif \
Middlewares/lvgl/src/libs/libjpeg_turbo \
Middlewares/lvgl/src/libs/libpng \
Middlewares/lvgl/src/libs/lodepng \
Middlewares/lvgl/src/libs/lz4 \
Middlewares/lvgl/src/libs/qrcode \
Middlewares/lvgl/src/libs/rle \
Middlewares/lvgl/src/libs/rlottie \
Middlewares/lvgl/src/libs/svg \
Middlewares/lvgl/src/libs/tiny_ttf \
Middlewares/lvgl/src/libs/tjpgd \
Middlewares/lvgl/src \
Middlewares/lvgl/src/misc/cache/class \
Middlewares/lvgl/src/misc/cache/instance \
Middlewares/lvgl/src/misc/cache \
Middlewares/lvgl/src/misc \
Middlewares/lvgl/src/osal \
Middlewares/lvgl/src/others/file_explorer \
Middlewares/lvgl/src/others/font_manager \
Middlewares/lvgl/src/others/fragment \
Middlewares/lvgl/src/others/gridnav \
Middlewares/lvgl/src/others/ime \
Middlewares/lvgl/src/others/imgfont \
Middlewares/lvgl/src/others/monkey \
Middlewares/lvgl/src/others/observer \
Middlewares/lvgl/src/others/snapshot \
Middlewares/lvgl/src/others/sysmon \
Middlewares/lvgl/src/others/test \
Middlewares/lvgl/src/others/vg_lite_tvg \
Middlewares/lvgl/src/others/xml \
Middlewares/lvgl/src/others/xml/parsers \
Middlewares/lvgl/src/stdlib/builtin \
Middlewares/lvgl/src/stdlib/clib \
Middlewares/lvgl/src/stdlib \
Middlewares/lvgl/src/stdlib/micropython \
Middlewares/lvgl/src/stdlib/rtthread \
Middlewares/lvgl/src/stdlib/uefi \
Middlewares/lvgl/src/themes/default \
Middlewares/lvgl/src/themes \
Middlewares/lvgl/src/themes/mono \
Middlewares/lvgl/src/themes/simple \
Middlewares/lvgl/src/tick \
Middlewares/lvgl/src/widgets/3dtexture \
Middlewares/lvgl/src/widgets/animimage \
Middlewares/lvgl/src/widgets/arc \
Middlewares/lvgl/src/widgets/bar \
Middlewares/lvgl/src/widgets/button \
Middlewares/lvgl/src/widgets/buttonmatrix \
Middlewares/lvgl/src/widgets/calendar \
Middlewares/lvgl/src/widgets/canvas \
Middlewares/lvgl/src/widgets/chart \
Middlewares/lvgl/src/widgets/checkbox \
Middlewares/lvgl/src/widgets/dropdown \
Middlewares/lvgl/src/widgets/image \
Middlewares/lvgl/src/widgets/imagebutton \
Middlewares/lvgl/src/widgets/keyboard \
Middlewares/lvgl/src/widgets/label \
Middlewares/lvgl/src/widgets/led \
Middlewares/lvgl/src/widgets/line \
Middlewares/lvgl/src/widgets/list \
Middlewares/lvgl/src/widgets/lottie \
Middlewares/lvgl/src/widgets/menu \
Middlewares/lvgl/src/widgets/msgbox \
Middlewares/lvgl/src/widgets/objx_templ \
Middlewares/lvgl/src/widgets/property \
Middlewares/lvgl/src/widgets/roller \
Middlewares/lvgl/src/widgets/scale \
Middlewares/lvgl/src/widgets/slider \
Middlewares/lvgl/src/widgets/span \
Middlewares/lvgl/src/widgets/spinbox \
Middlewares/lvgl/src/widgets/spinner \
Middlewares/lvgl/src/widgets/switch \
Middlewares/lvgl/src/widgets/table \
Middlewares/lvgl/src/widgets/tabview \
Middlewares/lvgl/src/widgets/textarea \
Middlewares/lvgl/src/widgets/tileview \
Middlewares/lvgl/src/widgets/win \

